### ISSUE TITLE
Final Capstone Project Kanban Board

### ISSUE THREAD

**Issue by nikoescobal** [nikoescobal/rentcopter#27]
#### We are three in this team:

 Team member A is @rpire 
 Team member B is @ReshyResh 
 Team member C is @Kalunge
 Team member D is @nikoescobal 

### Screenshot

![Rentcopter](https://user-images.githubusercontent.com/85108160/151180258-62d75d64-e08d-42a1-9fed-88fcdc0f226d.jpg)

**Comment by MuriloRoque** [comment]
Hi @Kalunge, @nikoescobal, @rpire, @ReshyResh, 

In my opinion, your project is complete! There is nothing else to say other than... it's time to start it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
